# Use postgres/example user/password credentials
#
version: '3.8'

services:

  db:
    image: postgres:${PG_VERSION}
    container_name: pg-demo-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 127.0.0.1:${PG_LOCALHOST_PORT}:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/bak:/bak
      - ./data/root:/root
      - ./storage:/storage
    networks:
      - pg-demo-net

  adminer:
    image: adminer
    container_name: pg-demo-adminer
    restart: always
    ports:
      - ${ADMINER_LOCALHOST_PORT}:8080
    networks:
      - pg-demo-net
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-demo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - pg-demo-net
    depends_on:
      - db

volumes:
  pgadmin:

networks:
  pg-demo-net:
    external: true


